### ISSUE TITLE
Breaking change to return Promise from `.on()`

### ISSUE THREAD

**Issue by FirstVertex** [tacheometry/SimpleSignals#8]
I have updated simplesignals with `npm update` command today and I have some breaking changes since `.on()` was marked as returning a Promise instead of returning RBXScriptConnection.

I didn't find any documentation about such change, and examples appear to show previous pattern (not Promise).  Any advice on how to handle that?  Why does it need to return Promise now? It will be a rather inconvenient refactor in several places of my code to change to async return type.  Is it necessary?

**Comment by tacheometry** [comment]
Hello. This update prevents yielding whenever you're connecting to multiple events in the same thread (e.g. same script) - #6. These now return `Promise<RBXScriptSignal>`. You wouldn't really need the return value of `.on` or similar though, you'd only use that for disconnecting from the event later:
```ts
// this example only runs the callback function of "someEvent" 5 times
import { Server as simple } from "@rbxts/simplesignals";

let numberOfTimesCalled: number = 0;
let connection: RBXScriptConnection;
function myCallback() { // this can return anything, as its return value isn't used anywhere in SimpleSignals
    numberOfTimesCalled++;
    if (numberOfTimesCalled === 5 && connection) {
        connection.Disconnect();
    }
}

simple.on("someEvent", myCallback).then(conn => {
    connection = conn;
});
```
If you only want to connect _once_, you should use `once`:
```ts
import { Server as simple} from "@rbxts/simplesignals";

simple.once("someEvent", () => {
    // whenever the event gets fired, the callback runs, and then the event will no longer get listened to
}); // once doesn't return anything
```

**Comment by tacheometry** [comment]
Sorry for the late reply, GitHub just doesn't really send me any notifications. You'll find me in the [roblox-ts Discord server](https://discord.com/invite/f6Rn6RY) though - my Discord tag is `RT#3913`. I also post updates there with changes under the `#packages-announcements` channel and I'm a lot quicker to respond there 🙂
